-- ============================================================================
-- Canon Platform - Seed Data (50 Quotes)
-- Mix of Classics + Profit Originals
-- ============================================================================

INSERT INTO posts (slug, quote_text, quote_attribution, source_title, source_author, source_type, source_chapter, talk_text, talk_tone, usage_action, usage_context, usage_time_minutes, categories, difficulty, reflection_prompt) VALUES

-- POWER (5 quotes)
('power-consent-unnecessary', 'The strongest systems don''t need consent. They make compliance the only logical path.', 'Profit', 'Canon: Systems Over Willpower', 'Arturious Castillo', 'profit-original', NULL, 'You don''t need more discipline. You need a system that makes the wrong choice harder than the right one. Motivation is a feeling. Systems are architecture.', 'brutal', 'Identify one habit you struggle with. Add 20 seconds of friction to the wrong choice.', 'Morning routine, phone usage, diet — wherever you break promises to yourself.', 5, ARRAY['systems', 'habits', 'discipline']::category_tag[], 'easy', 'What system failed you today? Not your willpower — the system.'),

('power-corner-boardroom', 'Power is power. The corner and the boardroom run on the same rules. Only the scale changes.', 'Profit', 'Canon: Power Dynamics', 'Arturious Castillo', 'profit-original', NULL, 'You think corporate politics is different from street politics? It''s not. It''s all about who controls the resources and who people are afraid to cross.', 'direct', 'Map the power structure in your workplace. Who actually makes decisions vs. who has the title?', 'Monday morning team meeting. Watch who speaks, who gets interrupted, whose ideas get adopted.', 10, ARRAY['power', 'leadership']::category_tag[], 'medium', 'Who has power over you that you''ve been pretending doesn''t?'),

('marcus-power-self', 'You have power over your mind—not outside events. Realize this, and you will find strength.', 'Marcus Aurelius', 'Meditations', 'Marcus Aurelius', 'classic', 'Book IX', 'The only thing you actually control is your response. Everything else is borrowed time and circumstance. Stop acting like the world owes you control it never promised.', 'brutal', 'When something goes wrong today, pause for 10 seconds before reacting. Choose your response.', 'Traffic, emails, criticism, delays — the small annoyances that usually own you.', 2, ARRAY['power', 'mindset', 'resilience']::category_tag[], 'easy', 'What outside event are you still trying to control?'),

('greene-power-law', 'Always say less than necessary. When you are trying to impress people with words, the more you say, the more common you appear.', 'Robert Greene', 'The 48 Laws of Power', 'Robert Greene', 'modern', 'Law 4', 'Talk less. Listen more. The person who speaks least controls the room because everyone else reveals their hand trying to fill the silence.', 'direct', 'In your next meeting, speak 50% less than usual. Take notes instead.', 'Any meeting where you usually dominate or feel the need to prove yourself.', 30, ARRAY['power', 'leadership']::category_tag[], 'medium', 'Who are you trying to impress with your words?'),

('profit-power-silence', 'Silence is a weapon. The person who waits to speak usually wins.', 'Profit', 'Canon: Strategic Communication', 'Arturious Castillo', 'profit-original', NULL, 'In prison, the guy who talked first usually lost. Same in business. Same in life. Let them talk. Let them reveal. Then move.', 'brutal', 'Wait 3 seconds before responding to any question today.', 'Negotiations, arguments, interviews — anywhere you feel pressure to answer immediately.', 5, ARRAY['power', 'execution']::category_tag[], 'medium', 'Where are you talking when you should be listening?'),

-- DISCIPLINE (5 quotes)
('discipline-myth', 'Discipline is a myth. What you call discipline, I call a system with no exit.', 'Profit', 'Canon: Systems Over Willpower', 'Arturious Castillo', 'profit-original', NULL, 'You don''t need more willpower. You need fewer choices. The most disciplined people don''t resist temptation — they engineer it out of existence.', 'brutal', 'Remove one temptation from your environment today. Don''t rely on willpower.', 'Your phone, junk food, distractions — make the wrong choice physically harder.', 10, ARRAY['discipline', 'systems', 'habits']::category_tag[], 'easy', 'What are you still trying to white-knuckle through?'),

('jocko-discipline-freedom', 'Discipline equals freedom.', 'Jocko Willink', 'Extreme Ownership', 'Jocko Willink', 'modern', NULL, 'It sounds backwards, but it''s true. The more disciplined your structure, the more mental bandwidth you have for what actually matters.', 'direct', 'Set one non-negotiable rule for tomorrow morning. No exceptions.', 'Wake time, workout, first task — pick one and make it automatic.', 5, ARRAY['discipline', 'execution']::category_tag[], 'medium', 'Where is your lack of discipline stealing your freedom?'),

('miyamoto-discipline-way', 'Think lightly of yourself and deeply of the world.', 'Miyamoto Musashi', 'The Book of Five Rings', 'Miyamoto Musashi', 'classic', 'The Water Book', 'You''re not that important. Your ego is the enemy. Focus on the work, the craft, the system — not on how you look doing it.', 'brutal', 'Do one task today without telling anyone about it. No social media, no announcement.', 'Your workout, your project, your good deed — keep it private.', 30, ARRAY['discipline', 'mindset']::category_tag[], 'hard', 'What are you doing for the performance of it?'),

('profit-discipline-identity', 'You don''t rise to the level of your goals. You fall to the level of your systems.', 'Profit', 'Canon: Systems Over Willpower', 'Arturious Castillo', 'profit-original', NULL, 'Goals are fantasies. Systems are reality. Your identity is just the sum of what you do repeatedly. Change the system, change the person.', 'direct', 'Pick one goal you''ve failed at. Replace it with a system: specific time, specific place, specific action.', 'Writing, working out, learning — turn the goal into a scheduled behavior.', 15, ARRAY['discipline', 'systems', 'habits']::category_tag[], 'medium', 'What goal are you still chasing without a system?'),

('clear-discipline-habit', 'You do not rise to the level of your goals. You fall to the level of your systems.', 'James Clear', 'Atomic Habits', 'James Clear', 'modern', NULL, 'Same idea, different voice. Your goals don''t matter if your daily behaviors don''t support them. Fix the inputs, the outputs fix themselves.', 'direct', 'Design your environment for the behavior you want. Make good choices obvious and bad choices invisible.', 'Your workspace, kitchen, phone — redesign for the person you want to become.', 20, ARRAY['discipline', 'habits', 'systems']::category_tag[], 'easy', 'What environment is working against your goals?'),

-- SYSTEMS (8 quotes)
('systems-architecture', 'Systems are architecture. Willpower is interior decoration.', 'Profit', 'Canon: Systems Over Willpower', 'Arturious Castillo', 'profit-original', NULL, 'You can''t decorate your way out of a bad foundation. Build the structure first. The motivation will follow — or it won''t, and you''ll succeed anyway.', 'brutal', 'Audit one system in your life. Is it built on willpower or structure?', 'Your morning routine, your diet, your work schedule — find the cracks.', 15, ARRAY['systems', 'discipline']::category_tag[], 'medium', 'What system is currently held together by your willpower?'),

('taleb-systems-antifragile', 'Some things benefit from shocks; they thrive and grow when exposed to volatility, randomness, disorder.', 'Nassim Taleb', 'Antifragile', 'Nassim Taleb', 'modern', NULL, 'Don''t just survive chaos. Build systems that get stronger from it. Stress + recovery = growth. No stress, no growth. No recovery, no growth.', 'provoking', 'Add intentional difficulty to one easy task today. Make it slightly harder on purpose.', 'Your workout, your commute, your routine — introduce controlled chaos.', 20, ARRAY['systems', 'resilience']::category_tag[], 'hard', 'Where are you avoiding necessary stress?'),

('senge-systems-thinking', 'The essence of systems thinking is to see the whole and its parts, not just the parts.', 'Peter Senge', 'The Fifth Discipline', 'Peter Senge', 'modern', NULL, 'You''re fixing symptoms while the root cause laughs at you. Step back. See the pattern. Fix the system, not the symptom.', 'direct', 'Identify one recurring problem. Ask "why" five times to find the system cause.', 'Any frustration that keeps happening — missed deadlines, conflicts, failures.', 30, ARRAY['systems', 'mindset']::category_tag[], 'medium', 'What symptom are you treating instead of the disease?'),

('profit-systems-friction', 'Friction is information. Pain is data about system failure.', 'Profit', 'Canon: Systems Over Willpower', 'Arturious Castillo', 'profit-original', NULL, 'Every time you procrastinate, every time you quit, every time you "just don''t feel like it" — that''s not a character flaw. That''s your system screaming at you.', 'brutal', 'Pick one thing you procrastinate on. Identify exactly where the friction is.', 'The task you keep putting off — what''s the first 30 seconds like?', 10, ARRAY['systems', 'friction', 'habits']::category_tag[], 'easy', 'What friction are you ignoring that''s killing your progress?'),

('munger-systems-mental-models', 'You''ve got to have models in your head. And you''ve got to array your experience on this latticework of models.', 'Charlie Munger', 'Poor Charlie''s Almanack', 'Charlie Munger', 'modern', NULL, 'One mental model is dangerous. You need multiple lenses to see reality. Incentives, feedback loops, second-order thinking — build your latticework.', 'direct', 'Learn one new mental model this week. Apply it to a current problem.', 'Inversion, second-order thinking, opportunity cost — pick one and use it.', 60, ARRAY['systems', 'mindset']::category_tag[], 'hard', 'What problem are you trying to solve with the wrong mental model?'),

('adams-systems-goals', 'Goals are for losers. Systems are for winners.', 'Scott Adams', 'How to Fail at Almost Everything', 'Scott Adams', 'modern', NULL, 'Goals are temporary. Systems are permanent. A goal is a finish line. A system is a lifestyle. Build the lifestyle, the finishes take care of themselves.', 'provoking', 'Convert one goal into a system: "I will write daily" instead of "I will write a book."', 'Any goal that feels overwhelming — break it into a repeatable process.', 10, ARRAY['systems', 'habits']::category_tag[], 'easy', 'What goal is making you feel like a loser?'),

('profit-systems-defaults', 'Your default state is your real state. Everything else is performance.', 'Profit', 'Canon: Systems Over Willpower', 'Arturious Castillo', 'profit-original', NULL, 'Who you are when you''re tired, when no one''s watching, when you ''don''t feel like it'' — that''s who you actually are. Design systems for that person.', 'brutal', 'Design a system for your worst day, not your best day.', 'What happens to your habits when you''re exhausted, stressed, or busy?', 15, ARRAY['systems', 'habits', 'discipline']::category_tag[], 'medium', 'What system only works when you''re at your best?'),

('taleb-systems-skin-in-game', 'Don''t tell me what you think, tell me what you have in your portfolio.', 'Nassim Taleb', 'Skin in the Game', 'Nassim Taleb', 'modern', NULL, 'Talk is cheap. Advice is free. The only opinions that matter come from people who bear the consequences of being wrong.', 'brutal', 'Before taking advice, ask: "What happens to this person if they''re wrong?"', 'Business advice, life advice, investment advice — follow the skin in the game.', 5, ARRAY['systems', 'power']::category_tag[], 'medium', 'Whose advice are you following that has no consequences?'),

('christensen-systems-jobs', 'People don''t want to buy a quarter-inch drill. They want a quarter-inch hole.', 'Clayton Christensen', 'Competing Against Luck', 'Clayton Christensen', 'modern', NULL, 'You''re selling features when you should be solving jobs. What''s the actual progress your customer wants to make?', 'direct', 'Reframe one thing you''re working on: what''s the "job to be done"?', 'Your product, your pitch, your relationship — what''s the underlying need?', 20, ARRAY['systems', 'execution']::category_tag[], 'medium', 'What feature are you building that no one needs?'),

-- RESILIENCE (5 quotes)
('resilience-obstacle-way', 'The impediment to action advances action. What stands in the way becomes the way.', 'Marcus Aurelius', 'Meditations', 'Marcus Aurelius', 'classic', 'Book V', 'The obstacle isn''t in your way. It IS the way. Every block is a lesson. Every resistance is training. Stop wishing it was easier.', 'brutal', 'Identify your biggest current obstacle. Write down three ways it can make you stronger.', 'The problem you''re avoiding, the difficulty you''re complaining about.', 15, ARRAY['resilience', 'mindset']::category_tag[], 'medium', 'What obstacle are you trying to avoid that''s actually your path?'),

('holiday-obstacle', 'The obstacle in the path becomes the path. Never forget, within every obstacle is an opportunity to improve our condition.', 'Ryan Holiday', 'The Obstacle Is the Way', 'Ryan Holiday', 'modern', NULL, 'Same idea, modern voice. The Stoics knew it. You need to remember it. The problem contains the solution.', 'direct', 'Turn one current problem into a project. Attack it systematically.', 'That thing you''re complaining about — make it your focus for the week.', 30, ARRAY['resilience', 'execution']::category_tag[], 'medium', 'What problem are you treating as an obstacle instead of raw material?'),

('frankl-resilience-meaning', 'Those who have a ''why'' to live, can bear with almost any ''how''.', 'Viktor Frankl', 'Man''s Search for Meaning', 'Viktor Frankl', 'classic', NULL, 'Meaning is fuel. When you know why you''re doing something, the how becomes bearable. Even the unbearable becomes bearable.', 'empathetic', 'Reconnect with your ''why'' today. Write it down. Read it when things get hard.', 'Your work, your relationship, your struggle — why does it matter?', 10, ARRAY['resilience', 'mindset']::category_tag[], 'easy', 'What ''why'' have you lost sight of?'),

('profit-resilience-heat', 'Heat reveals cracks. Pressure shows weak joints. That''s not cruelty — that''s information.', 'Profit', 'Canon: Systems Over Willpower', 'Arturious Castillo', 'profit-original', NULL, 'You want to know if your system works? Stress-test it. Most people build for perfect conditions and wonder why they break. Build for the storm.', 'brutal', 'Intentionally add pressure to one system today. See where it cracks.', 'Your schedule, your habits, your relationships — find the weak joint before life does.', 20, ARRAY['resilience', 'systems']::category_tag[], 'hard', 'What system have you never actually tested under pressure?'),

('duckworth-resilience-grit', 'Grit is passion and perseverance for long-term goals.', 'Angela Duckworth', 'Grit', 'Angela Duckworth', 'modern', NULL, 'Talent is overrated. Effort counts twice. The people who win aren''t necessarily the most talented — they''re the ones who don''t quit.', 'direct', 'Pick one long-term goal. Commit to working on it for just 10 minutes today.', 'The project you''ve abandoned, the skill you''ve neglected — restart small.', 10, ARRAY['resilience', 'discipline']::category_tag[], 'easy', 'What did you quit that you should have gritted through?'),

-- EXECUTION (5 quotes)
('execution-done-perfect', 'Done is better than perfect. Perfect is the enemy of shipped.', 'Profit', 'Canon: Execution Over Ideas', 'Arturious Castillo', 'profit-original', NULL, 'You''re polishing a turd. Ship it. Get feedback. Iterate. The perfect plan that never executes is worthless. The mediocre plan that ships changes everything.', 'brutal', 'Ship something imperfect today. Publish, send, release — before you''re ready.', 'The email you''ve drafted 10 times, the post you''re over-editing, the project that''s 90% done.', 5, ARRAY['execution', 'discipline']::category_tag[], 'medium', 'What are you perfecting that should just be shipped?'),

('musk-execution-first', 'If you give yourself 30 days to clean your home, it will take 30 days. If you give yourself 3 hours, it will take 3 hours.', 'Elon Musk', 'Various Interviews', 'Elon Musk', 'modern', NULL, 'Time expands to fill the space you give it. Constraint creates focus. Deadlines drive decisions. Stop giving yourself unlimited time.', 'direct', 'Set an aggressive deadline for one task today. Half what feels reasonable.', 'The project that''s dragging on, the decision you''re delaying — add pressure.', 5, ARRAY['execution', 'systems']::category_tag[], 'medium', 'What task is expanding to fill the time you gave it?'),

('allen-execution-next-action', 'You don''t actually do a project; you can only do action steps related to it.', 'David Allen', 'Getting Things Done', 'David Allen', 'modern', NULL, 'Projects are overwhelming because they''re not actionable. "Launch website" isn''t a task. "Write homepage headline" is. Break it down.', 'direct', 'Take one overwhelming project. Write down the very next physical action.', 'Not the plan. Not the strategy. The literal next thing you can do with your hands.', 10, ARRAY['execution', 'systems']::category_tag[], 'easy', 'What project is overwhelming you because it''s not broken down?'),

('profit-execution-precision', 'Precision over power. Finesse over force.', 'Profit', 'Canon: Strategic Execution', 'Arturious Castillo', 'profit-original', NULL, 'You''re trying to muscle through. Stop. Find the leverage point. One precise move beats a hundred sloppy punches. This is true in fighting, business, and life.', 'brutal', 'Identify one task you''re brute-forcing. Find the leverage point instead.', 'The relationship you''re forcing, the problem you''re attacking head-on — find the angle.', 15, ARRAY['execution', 'power']::category_tag[], 'hard', 'Where are you using force when you should be using precision?'),

('peters-execution-bias', 'Bias for action.', 'Tom Peters', 'In Search of Excellence', 'Tom Peters', 'modern', NULL, 'Most people analyze until the opportunity passes. The winners act, then adjust. You can''t steer a parked car. Start moving.', 'direct', 'Make one decision today without overthinking. You have 60 seconds.', 'The choice you''ve been agonizing over — trust your gut and move.', 1, ARRAY['execution', 'mindset']::category_tag[], 'easy', 'What decision are you still analyzing that you should just make?'),

-- MINDSET (5 quotes)
('mindset-fixed-growth', 'In a growth mindset, challenges are exciting rather than threatening.', 'Carol Dweck', 'Mindset', 'Carol Dweck', 'modern', NULL, 'Fixed mindset: failure is identity. Growth mindset: failure is data. One destroys you. One develops you. Choose.', 'direct', 'Reframe one recent failure as data. What did it teach you?', 'The rejection, the mistake, the embarrassment — extract the lesson.', 10, ARRAY['mindset', 'resilience']::category_tag[], 'easy', 'What failure are you still treating as identity instead of information?'),

('seneca-mindset-time', 'It is not that we have a short time to live, but that we waste a lot of it.', 'Seneca', 'On the Shortness of Life', 'Seneca', 'classic', NULL, 'You have enough time. You''re just spending it on bullshit. Social media, drama, waiting for permission — all theft of your limited days.', 'brutal', 'Audit your last 24 hours. What percentage was spent on what actually matters?', 'Your screen time, your conversations, your mental loops — be honest.', 15, ARRAY['mindset', 'discipline']::category_tag[], 'medium', 'What are you spending time on that you''ll regret on your deathbed?'),

('kahneman-mindset-thinking', 'Nothing in life is as important as you think it is, while you are thinking about it.', 'Daniel Kahneman', 'Thinking, Fast and Slow', 'Daniel Kahneman', 'modern', NULL, 'Your brain magnifies whatever you focus on. The crisis feels existential because you''re looking at it. Zoom out. It''s probably smaller than it feels.', 'empathetic', 'When you''re overwhelmed, ask: "Will this matter in 5 years?"', 'The crisis, the conflict, the stress — apply the 5-year test.', 2, ARRAY['mindset', 'systems']::category_tag[], 'easy', 'What feels huge right now that won''t matter in 5 years?'),

('profit-mindset-identity', 'You are not your thoughts. You are your actions.', 'Profit', 'Canon: Identity Systems', 'Arturious Castillo', 'profit-original', NULL, 'You can think about change all day. You can journal about it. You can visualize it. But you''re only changed when your behavior changes. Everything else is fantasy.', 'brutal', 'Pick one identity you want. Do one action that proves it today.', '"I''m a writer" — write. "I''m fit" — move. Action before identity.', 10, ARRAY['mindset', 'habits']::category_tag[], 'medium', 'What identity are you claiming without the actions to back it?'),

('epictetus-mindset-control', 'Make the best use of what is in your power, and take the rest as it happens.', 'Epictetus', 'Discourses', 'Epictetus', 'classic', NULL, 'The dichotomy of control: some things are up to you, most things aren''t. Focus entirely on the first category. Accept the second completely.', 'direct', 'Divide your current worries into "can control" and "can''t control." Burn the second list.', 'Your worries, your anxieties, your plans — sort them honestly.', 10, ARRAY['mindset', 'systems']::category_tag[], 'medium', 'What are you trying to control that you never could?'),

-- HABITS (5 quotes)
('habits-atomic-clear', 'You do not rise to the level of your goals. You fall to the level of your systems.', 'James Clear', 'Atomic Habits', 'James Clear', 'modern', NULL, 'Goals are the destination. Systems are the vehicle. You can''t goal your way to success. You system your way there, one small habit at a time.', 'direct', 'Make one habit 1% better today. Smaller than you think.', 'Too small to fail: one pushup, one sentence, one minute.', 5, ARRAY['habits', 'systems']::category_tag[], 'easy', 'What habit are you trying to build that''s too big to sustain?'),

('duhigg-habit-loop', 'Change might not be fast and it isn''t always easy. But with time and effort, almost any habit can be reshaped.', 'Charles Duhigg', 'The Power of Habit', 'Charles Duhigg', 'modern', NULL, 'Cue → Routine → Reward. That''s the loop. You can''t break it, but you can hijack it. Keep the cue and reward, change the routine.', 'direct', 'Identify one habit loop. Change the routine while keeping cue and reward.', 'Your phone habit, your snacking, your procrastination — find the trigger.', 20, ARRAY['habits', 'systems']::category_tag[], 'medium', 'What habit loop are you trying to break instead of hijack?'),

('profit-habits-identity', 'Every action you take is a vote for the type of person you wish to become.', 'Profit', 'Canon: Identity Systems', 'Arturious Castillo', 'profit-original', NULL, 'No single action defines you. But the pattern does. Every workout is a vote for "I''m an athlete." Every cigarette is a vote for "I''m a smoker." Vote carefully.', 'brutal', 'Count your votes today. What identity are you actually building?', 'Your actions in the last 24 hours — what do they add up to?', 10, ARRAY['habits', 'mindset']::category_tag[], 'easy', 'What identity are you voting for with your daily actions?'),

('fogg-habit-tiny', 'Take a behavior you want, make it tiny, find where it fits naturally in your life, and nurture its growth.', 'BJ Fogg', 'Tiny Habits', 'BJ Fogg', 'modern', NULL, 'Start stupidly small. After I [existing habit], I will [tiny new habit]. Celebrate immediately. That''s the formula. It works because it''s too small to fail.', 'direct', 'Create one tiny habit: "After I [existing habit], I will [new tiny behavior]."', 'After coffee, after bathroom, after sitting down — anchor to existing.', 5, ARRAY['habits', 'systems']::category_tag[], 'easy', 'What habit are you making too big to start?'),

('covey-habits-sharpen', 'Sharpen the saw.', 'Stephen Covey', 'The 7 Habits of Highly Effective People', 'Stephen Covey', 'modern', 'Habit 7', 'You''re too busy sawing to sharpen the blade. Production capacity matters more than production. Rest, learn, recover — it''s not lazy, it''s strategic.', 'empathetic', 'Schedule one hour this week for "sharpening the saw" — rest, learning, or recovery.', 'The thing you''ve been neglecting because you''re "too busy."', 60, ARRAY['habits', 'resilience']::category_tag[], 'medium', 'What saw needs sharpening that you''ve been too busy to sharpen?'),

-- LEADERSHIP (5 quotes)
('leadership-extreme', 'Extreme ownership. Leaders must own everything in their world. There is no one else to blame.', 'Jocko Willink', 'Extreme Ownership', 'Jocko Willink', 'modern', NULL, 'Your team failed? Your fault. The project tanked? Your fault. Someone else messed up? Still your fault — you hired them, trained them, or didn''t check their work.', 'brutal', 'Identify one thing you''ve been blaming on others. Take full ownership today.', 'The missed deadline, the bad result, the team failure — it''s yours.', 10, ARRAY['leadership', 'power']::category_tag[], 'hard', 'What are you still blaming on someone else?'),

('sinek-leadership-why', 'People don''t buy what you do; they buy why you do it.', 'Simon Sinek', 'Start with Why', 'Simon Sinek', 'modern', NULL, 'Features are commodities. Purpose is magnetic. Lead with why, not what. The same product with a better story wins every time.', 'direct', 'Rewrite one thing you''re pitching. Lead with why, not what.', 'Your product, your idea, your request — what''s the underlying belief?', 20, ARRAY['leadership', 'execution']::category_tag[], 'medium', 'Where are you leading with what instead of why?'),

('profit-leadership-shadow', 'Your team performs to the standard you walk past.', 'Profit', 'Canon: Leadership Systems', 'Arturious Castillo', 'profit-original', NULL, 'You can''t enforce rules you break. You can''t demand excellence you don''t model. Your shadow is the real standard — everything else is just talk.', 'brutal', 'Identify one standard you''ve been preaching but not practicing. Fix it today.', 'The behavior you criticize in others that you also do — start with you.', 15, ARRAY['leadership', 'discipline']::category_tag[], 'hard', 'What standard are you walking past?'),

('heifetz-leadership-adaptive', 'The most common source of leadership failure is treating adaptive challenges as technical problems.', 'Ronald Heifetz', 'The Practice of Adaptive Leadership', 'Ronald Heifetz', 'modern', NULL, 'Technical problems have known solutions. Adaptive challenges require people to change. Most leaders apply technical fixes to adaptive problems and wonder why nothing changes.', 'direct', 'Identify one problem you''ve been treating as technical that''s actually adaptive.', 'The conflict, the resistance, the culture issue — it needs people change, not process change.', 30, ARRAY['leadership', 'systems']::category_tag[], 'hard', 'What adaptive challenge are you trying to solve with a technical fix?'),

('collins-leadership-level5', 'Level 5 leaders channel their ego needs away from themselves and into the larger goal of building a great company.', 'Jim Collins', 'Good to Great', 'Jim Collins', 'modern', NULL, 'It''s not about you. The best leaders are ambitious for the cause, not themselves. Humility + will = Level 5.', 'empathetic', 'Check your motivation on one current project. Is it for you or for the mission?', 'The credit you want, the recognition you''re chasing — redirect it.', 10, ARRAY['leadership', 'mindset']::category_tag[], 'medium', 'Where is your ego getting in the way of the mission?'),

-- FRICTION (5 quotes)
('friction-design', 'Design your systems so the right choice is the easy choice.', 'Profit', 'Canon: Systems Over Willpower', 'Arturious Castillo', 'profit-original', NULL, 'Friction is a design choice. You can add it or remove it. Good habits need less friction. Bad habits need more. You''re the architect of both.', 'direct', 'Add friction to one bad habit. Remove friction from one good habit.', 'Your phone charger location, your gym clothes, your snack drawer — redesign.', 20, ARRAY['friction', 'habits', 'systems']::category_tag[], 'easy', 'What good habit has too much friction? What bad habit has too little?'),

('eyal-friction-triggers', 'Triggers cue behaviors. If you want to change a habit, you must first understand its trigger.', 'Nir Eyal', 'Hooked', 'Nir Eyal', 'modern', NULL, 'Every habit starts with a trigger. Internal (boredom, anxiety) or external (notification, location). Map the trigger, you can change the response.', 'direct', 'Map the trigger for one habit you want to change. What happens right before?', 'The urge to check your phone, the craving for sugar — what triggered it?', 10, ARRAY['friction', 'habits']::category_tag[], 'easy', 'What trigger are you ignoring that drives your unwanted habits?'),

('thaler-friction-nudge', 'There are no neutral designs. Every choice architecture nudges one way or another.', 'Richard Thaler', 'Nudge', 'Richard Thaler', 'modern', NULL, 'Default options matter. Presentation order matters. Framing matters. You''re being nudged constantly — or you''re the one nudging yourself.', 'provoking', 'Audit one choice you make regularly. How is the environment nudging you?', 'Your grocery store layout, your app notifications, your default options.', 15, ARRAY['friction', 'systems']::category_tag[], 'medium', 'What choice are you making on autopilot that''s being nudged against you?'),

('profit-friction-resistance', 'Resistance is data. Procrastination is information. Listen to it.', 'Profit', 'Canon: Systems Over Willpower', 'Arturious Castillo', 'profit-original', NULL, 'You don''t procrastinate because you''re lazy. You procrastinate because the task is unclear, too big, or not actually aligned. The resistance is telling you something.', 'brutal', 'Pick one thing you''re procrastinating on. Ask: Is it unclear? Too big? Wrong goal?', 'The task that''s been on your list for weeks — diagnose the resistance.', 10, ARRAY['friction', 'execution']::category_tag[], 'medium', 'What resistance are you fighting instead of listening to?'),

('fogg-friction-ability', 'Behavior happens when motivation and ability converge. If motivation is low, increase ability.', 'BJ Fogg', 'Tiny Habits', 'BJ Fogg', 'modern', NULL, 'Make it easier. That''s the whole game. When you don''t feel like it, the only lever you have is ability. Reduce the friction until it''s harder NOT to do it.', 'direct', 'Make one habit so easy you''d feel stupid NOT doing it.', 'One minute, one sentence, one step — embarrassingly small.', 5, ARRAY['friction', 'habits']::category_tag[], 'easy', 'What habit are you making too hard for your current motivation level?'),

-- COMPLIANCE (5 quotes)
('compliance-prison', 'Prison taught me: The strongest systems don''t need consent. They make compliance the only logical path.', 'Profit', 'Canon: Systems Over Willpower', 'Arturious Castillo', 'profit-original', NULL, 'You don''t need willpower when the system is designed right. The best systems make the wrong choice harder, the right choice easier. Compliance becomes automatic.', 'brutal', 'Design one system where the right choice is the only logical choice.', 'Your environment, your schedule, your defaults — remove the option to fail.', 20, ARRAY['compliance', 'systems', 'discipline']::category_tag[], 'hard', 'What system still relies on your consent instead of your compliance?'),

('cialdini-compliance-consistency', 'Once we make a choice or take a stand, we will encounter personal and interpersonal pressures to behave consistently with that commitment.', 'Robert Cialdini', 'Influence', 'Robert Cialdini', 'modern', NULL, 'Consistency is a weapon. Small commitments lead to big ones. Public commitments are stronger than private ones. Use this on yourself.', 'direct', 'Make a public commitment to one habit today. Post it, tell someone, make it real.', 'The habit you''ve been keeping private — make it visible.', 5, ARRAY['compliance', 'habits']::category_tag[], 'easy', 'What commitment are you keeping private that should be public?'),

('heath-compliance-switch', 'What looks like a people problem is often a situation problem.', 'Chip Heath', 'Switch', 'Chip Heath', 'modern', NULL, 'Don''t blame the rider (rational mind). Don''t blame the elephant (emotional mind). Fix the path (environment). The path shapes behavior more than motivation.', 'direct', 'Change the environment for one behavior instead of trying to change the person.', 'The workspace, the kitchen, the phone — redesign the path.', 30, ARRAY['compliance', 'systems']::category_tag[], 'medium', 'What people problem is actually a situation problem?'),

('profit-compliance-defaults', 'Your defaults are your destiny.', 'Profit', 'Canon: Systems Over Willpower', 'Arturious Castillo', 'profit-original', NULL, 'What happens when you''re not thinking? That''s your real system. Everything else is theater. Design your defaults carefully — they''re running your life.', 'brutal', 'Audit your defaults: What do you eat when you''re tired? What do you do when bored?', 'The autopilot behaviors — they''re either designed or accidental.', 15, ARRAY['compliance', 'habits', 'systems']::category_tag[], 'medium', 'What default is running your life that you never chose?'),

('milgram-compliance-obedience', 'Ordinary people, simply doing their jobs, can become agents in a terrible destructive process.', 'Stanley Milgram', 'Obedience to Authority', 'Stanley Milgram', 'modern', NULL, 'Compliance can be dangerous. Question authority. Question systems. Even the ones you built yourself. Blind obedience — even to your own rules — is a trap.', 'provoking', 'Question one system or rule you''ve been following blindly. Does it still serve you?', 'Your routine, your beliefs, your automatic compliance — challenge one.', 20, ARRAY['compliance', 'mindset']::category_tag[], 'hard', 'What are you complying with that you should be questioning?');

-- Update engagement counts to realistic starting values
UPDATE posts SET 
  likes_count = floor(random() * 1000 + 100),
  saves_count = floor(random() * 500 + 50),
  shares_count = floor(random() * 200 + 20),
  reflections_count = floor(random() * 100 + 10),
  completions_count = floor(random() * 2000 + 500);