-- ============================================================================
-- Canon Platform - Seed Data (50 Quotes)
-- Mix of Classics + Profit Originals
-- Run this AFTER database.sql
-- ============================================================================

INSERT INTO posts (slug, quote_text, quote_attribution, source_title, source_author, source_type, source_chapter, talk_text, talk_tone, usage_action, usage_context, usage_time_minutes, categories, difficulty, reflection_prompt) VALUES

-- POWER (5 quotes)
('power-consent-unnecessary', 'The strongest systems don''t need consent. They make compliance the only logical path.', 'Profit', 'Canon: Systems Over Willpower', 'Arturious Castillo', 'profit-original', NULL, 'You don''t need more discipline. You need a system that makes the wrong choice harder than the right one. Motivation is a feeling. Systems are architecture.', 'brutal', 'Identify one habit you struggle with. Add 20 seconds of friction to the wrong choice.', 'Morning routine, phone usage, diet — wherever you break promises to yourself.', 5, ARRAY['systems', 'habits', 'discipline']::category_tag[], 'easy', 'What system failed you today? Not your willpower — the system.'),

('power-corner-boardroom', 'Power is power. The corner and the boardroom run on the same rules. Only the scale changes.', 'Profit', 'Canon: Power Dynamics', 'Arturious Castillo', 'profit-original', NULL, 'You think corporate politics is different from street politics? It''s not. It''s all about who controls the resources and who people are afraid to cross.', 'direct', 'Map the power structure in your workplace. Who actually makes decisions vs. who has the title?', 'Monday morning team meeting. Watch who speaks, who gets interrupted, whose ideas get adopted.', 10, ARRAY['power', 'leadership']::category_tag[], 'medium', 'Who has power over you that you''ve been pretending doesn''t?'),

('marcus-power-self', 'You have power over your mind—not outside events. Realize this, and you will find strength.', 'Marcus Aurelius', 'Meditations', 'Marcus Aurelius', 'classic', 'Book IX', 'The only thing you actually control is your response. Everything else is borrowed time and circumstance. Stop acting like the world owes you control it never promised.', 'brutal', 'When something goes wrong today, pause for 10 seconds before reacting. Choose your response.', 'Traffic, emails, criticism, delays — the small annoyances that usually own you.', 2, ARRAY['power', 'mindset', 'resilience']::category_tag[], 'easy', 'What outside event are you still trying to control?'),

('greene-power-law', 'Always say less than necessary. When you are trying to impress people with words, the more you say, the more common you appear.', 'Robert Greene', 'The 48 Laws of Power', 'Robert Greene', 'modern', 'Law 4', 'Talk less. Listen more. The person who speaks least controls the room because everyone else reveals their hand trying to fill the silence.', 'direct', 'In your next meeting, speak 50% less than usual. Take notes instead.', 'Any meeting where you usually dominate or feel the need to prove yourself.', 30, ARRAY['power', 'leadership']::category_tag[], 'medium', 'Who are you trying to impress with your words?'),

('profit-power-silence', 'Silence is a weapon. The person who waits to speak usually wins.', 'Profit', 'Canon: Strategic Communication', 'Arturious Castillo', 'profit-original', NULL, 'In prison, the guy who talked first usually lost. Same in business. Same in life. Let them talk. Let them reveal. Then move.', 'brutal', 'Wait 3 seconds before responding to any question today.', 'Negotiations, arguments, interviews — anywhere you feel pressure to answer immediately.', 5, ARRAY['power', 'execution']::category_tag[], 'medium', 'Where are you talking when you should be listening?'),

-- DISCIPLINE (5 quotes)
('discipline-myth', 'Discipline is a myth. What you call discipline, I call a system with no exit.', 'Profit', 'Canon: Systems Over Willpower', 'Arturious Castillo', 'profit-original', NULL, 'You don''t need more willpower. You need fewer choices. The most disciplined people don''t resist temptation — they engineer it out of existence.', 'brutal', 'Remove one temptation from your environment today. Don''t rely on willpower.', 'Your phone, junk food, distractions — make the wrong choice physically harder.', 10, ARRAY['discipline', 'systems', 'habits']::category_tag[], 'easy', 'What are you still trying to white-knuckle through?'),

('jocko-discipline-freedom', 'Discipline equals freedom.', 'Jocko Willink', 'Extreme Ownership', 'Jocko Willink', 'modern', NULL, 'It sounds backwards, but it''s true. The more disciplined your structure, the more mental bandwidth you have for what actually matters.', 'direct', 'Set one non-negotiable rule for tomorrow morning. No exceptions.', 'Wake time, workout, first task — pick one and make it automatic.', 5, ARRAY['discipline', 'execution']::category_tag[], 'medium', 'Where is your lack of discipline stealing your freedom?'),

('miyamoto-discipline-way', 'Think lightly of yourself and deeply of the world.', 'Miyamoto Musashi', 'The Book of Five Rings', 'Miyamoto Musashi', 'classic', 'The Water Book', 'You''re not that important. Your ego is the enemy. Focus on the work, the craft, the system — not on how you look doing it.', 'brutal', 'Do one task today without telling anyone about it. No social media, no announcement.', 'Your workout, your project, your good deed — keep it private.', 30, ARRAY['discipline', 'mindset']::category_tag[], 'hard', 'What are you doing for the performance of it?'),

('profit-discipline-identity', 'You don''t rise to the level of your goals. You fall to the level of your systems.', 'Profit', 'Canon: Systems Over Willpower', 'Arturious Castillo', 'profit-original', NULL, 'Goals are fantasies. Systems are reality. Your identity is just the sum of what you do repeatedly. Change the system, change the person.', 'direct', 'Pick one goal you''ve failed at. Replace it with a system: specific time, specific place, specific action.', 'Writing, working out, learning — turn the goal into a scheduled behavior.', 15, ARRAY['discipline', 'systems', 'habits']::category_tag[], 'medium', 'What goal are you still chasing without a system?'),

('clear-discipline-habit', 'You do not rise to the level of your goals. You fall to the level of your systems.', 'James Clear', 'Atomic Habits', 'James Clear', 'modern', NULL, 'Same idea, different voice. Your goals don''t matter if your daily behaviors don''t support them. Fix the inputs, the outputs fix themselves.', 'direct', 'Design your environment for the behavior you want. Make good choices obvious and bad choices invisible.', 'Your workspace, kitchen, phone — redesign for the person you want to become.', 20, ARRAY['discipline', 'habits', 'systems']::category_tag[], 'easy', 'What environment is working against your goals?');